ProjectWeb/Controllers/ProController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectWeb.Models;

namespace ProjectWeb.Controllers
{
    public class ProController : Controller
    {
        private dbshopgameEntities db = new dbshopgameEntities();

        // GET: Pro
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Pro/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Pro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pro/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SanPham,ID_DanhMuc,TenSanPham,HinhAnh,MaSanPham,GiaGoc,Sale,TinhTrang,Video,HinhAnhGame,HinhAnhGame1,HinhAnhGame2,MoTa,MoTa1,MoTa2,Tags")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Pro/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Pro/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SanPham,ID_DanhMuc,TenSanPham,HinhAnh,MaSanPham,GiaGoc,Sale,TinhTrang,Video,HinhAnhGame,HinhAnhGame1,HinhAnhGame2,MoTa,MoTa1,MoTa2,Tags")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Pro/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Pro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectWeb/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectWeb.Models;

namespace ProjectWeb.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductDetail(int Iddetail)
        {
            dbshopgameEntities db = new dbshopgameEntities();
            Product prodetail = db.Products.Where(p => p.ID_SanPham == Iddetail).SingleOrDefault();
            return View(prodetail);
        }
        //[ChildActionOnly]
        public ActionResult getCategory()
        {
            dbshopgameEntities db = new dbshopgameEntities();
            List<Category> listDanhMuc = db.Categories.ToList<Category>();
            return PartialView(listDanhMuc);
        }
        public ActionResult ListProduct(int Iddanhmuc)
        {
            dbshopgameEntities db = new dbshopgameEntities();
            List<Product> listProduct = db.Products.Where(p => p.ID_DanhMuc == Iddanhmuc).ToList();
            return View(listProduct);
        }


    }
}

ProjectWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectWeb.Models;
using System.Security.Cryptography;
using System.Text;


namespace ProjectWeb.Controllers
{
    public class UserController : Controller
    {
        dbshopgameEntities db = new dbshopgameEntities();
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterModel user)
        {
            try
            {
                dbshopgameEntities db = new dbshopgameEntities();
                if (ModelState.IsValid == true)
                {
                    UserManager usermanager = new UserManager();
                    if (usermanager.checkUserName(user.username) == false && usermanager.checkEmail(user.email) == false)/*chưa tồn tại nên tạo mới*/
                    {
                        Account newuser = new Account();
                        newuser.UserName = user.username;
                        newuser.Name = user.name;
                        newuser.Password = user.password;
                        newuser.Email = user.email;
                        //newuser.SĐT = user.SĐT;
                        //newuser.DiaChi = user.DiaChi;

                        //mã hóa password
                        SHA256 md5 = new SHA256CryptoServiceProvider();
                        Byte[] originalBytes = ASCIIEncoding.Default.GetBytes(newuser.Password);
                        Byte[] encodedBytes = md5.ComputeHash(originalBytes);
                        newuser.Password = BitConverter.ToString(encodedBytes);

                        db.Accounts.Add(newuser);
                        db.SaveChanges();
                        //ViewBag.dangkythanhcong = "Đã đăng ký thành công";
                        //return View();
                        Session["Register"] = "Đăng kí thành công";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        //return View("FailRegister");
                        ModelState.AddModelError("RegisterFail", "Tài khoản đã tồn tại");
                        ViewBag.error = "Tai khoan da ton tai";
                    }
                    ViewBag.dangkythanhcong = "đã đăng ký thành công";
                }                
            }
            catch(Exception ex)
            {

            }
            return View();
        }
        public ActionResult FailRegister()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                string taikhoan = fc["TxtTaikhoan"].ToString();
                string matkhau = fc["TxtMatkhau"].ToString();

                SHA256 md5 = new SHA256CryptoServiceProvider();
                Byte[] originalBytes = ASCIIEncoding.Default.GetBytes(matkhau);
                Byte[] encodedBytes = md5.ComputeHash(originalBytes);
                matkhau = BitConverter.ToString(encodedBytes);

                Account user = db.Accounts.SingleOrDefault(x => x.UserName == taikhoan && x.Password == matkhau);

                if (user != null)
                {
                    Session["Logged"] = "Xin chào" + " " + user.Name;



                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    ModelState.AddModelError("Login", "User name hoặc password sai");
                    ViewBag.thongbao = "Tên tài khoản hoặc mật khẩu sai";
                    return View();
                }
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session["Logged"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

ProjectWeb/Views/_LayoutWeb.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Nintendo Game Shop</title>
    <meta name="keywords" content="Book Store Template, Free CSS Template, CSS Website Layout, CSS, HTML">
    <meta name="description" content="Book Store Template, Free CSS Template, Download CSS Website">
    <link href="~/templatemo_style.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>
    <!--  Free CSS Templates from www.templatemo.com -->
    <div id="templatemo_container">
        <div id="templatemo_menu">
            <ul>
                <li><a href='@Url.Action("Index","Home")' class="current">Home</a></li>
                <li><a href="subpage.html">Search</a></li>

                @*<li><a href="https://localhost:44368/Product/ListProduct?Iddanhmuc=2">Games Nintendo</a></li>
        <li><a href="https://localhost:44368/Product/ListProduct?Iddanhmuc=4">Games PS4</a></li>*@

                <li>
                    <a href="subpage.html">New Releases</a>
                </li>

                <li style="float:right"><a class="active" href='@Url.Action("Register","User")'>Register</a></li>
                @*<li style="float:right"><a class="active" href='@Url.Action("Login","User")'>Sign In</a></li>*@
                @if (Session["Logged"] != null)
                {
                    <li style="float:right"><a href='@Url.Action("Index","Pro")' class="current">Admin</a></li>
                    <li style="float:right">@Html.ActionLink("Log Out", "Logout", "User")</li>
                    <li style="float:right">@Html.ActionLink((string)Session["Logged"], "Contant", "Home")</li>

                    @*<li style="float:right">@Session["Logged"]</li>*@
                }
                else
                {
                    <li style="float:right">@Html.ActionLink("Log In", "Login", "User")</li>
                }

                <li>
                    <i class="fa fa-shopping-cart" style="float:right; font-size:medium; color:turquoise">
                        <span>@Session["count"]</span>
                    </i>

                </li>

            </ul>
        </div> <!-- end of menu -->

        <div id="templatemo_header">
            <div id="templatemo_special_offers">
                <p>
                    <span>Tặng dán màn hình</span> và còn nhiều ưu đãi khi mua hàng tại shop
                </p>
                <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
            </div>


            <div id="templatemo_new_books">
                <ul>
                    <li>Game Pokemon Sword</li>
                    <li>Game Pokemon Shield</li>
                    <li>PS4 limited edition</li>
                </ul>
                <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
            </div>
        </div> <!-- end of header -->

        <div id="templatemo_content">

            <div id="templatemo_content_left">
                <div class="templatemo_content_left_section">




                    @Html.Action("getCategory", "Product")




                </div>
                <div class="templatemo_content_left_section">
                    <h1>Bestsellers</h1>
                    <ul>
                        <li><a href="https://localhost:44368/Product/ProductDetail?Iddetail=9">Game Pokemon Sword</a></li>
                        <li><a href="https://localhost:44368/Product/ProductDetail?Iddetail=34">Game Pokemon Shield</a></li>
                        <li><a href="https://localhost:44368/Product/ProductDetail?Iddetail=8">Game Fire Emblem: Three House</a></li>
                        <li><a href="https://localhost:44368/Product/ProductDetail?Iddetail=33">Game Legend of Zelda: BOTW</a></li>
                        @*<li><a href="#">Maece nas metus</a></li>
                            <li><a href="#">In sed risus ac feli</a></li>
                            <li><a href="http://www.flashmo.com" target="_parent">Flash Templates</a></li>
                            <li><a href="http://www.templatemo.com" target="_parent">CSS Templates</a></li>
                            <li><a href="http://www.webdesignmo.com" target="_parent">Web Design</a></li>
                            <li><a href="http://www.photovaco.com" target="_parent">Free Photos</a></li>*@
                    </ul>
                </div>

                <div class="templatemo_content_left_section">
                    <h1>Information</h1>
                    <ul>
                        <li><a href="index.html"><img src="https://otsukai.com/public/item/23408/original-5dbe400710928.jpeg" alt="css template ad" height="800%" width="100%"></a></li>
                        <li>Một trong những tựa game siêu phẩm của ATLUS đã trở lại</li>
                        @*<li><a href="index.html"><img src="https://bom.to/x5yLFD" alt="css template ad" height="800%" width="100%"></a></li>*@
                    </ul>
                </div>

                <div class="templatemo_content_left_section">
                    <a href="http://validator.w3.org/check?uri=referer"><img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0"></a>
                    <a href="~/http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" vspace="8" border="0"></a>


                </div>
            </div> <!-- end of content left -->

            <div id="templatemo_content_right">


                @RenderBody()


                
                
            </div> <!-- end of content right -->

            <div class="cleaner_with_height">&nbsp;</div>
        </div> <!-- end of content -->

        <div id="templatemo_footer">

            <a href="subpage.html">Home</a> | <a href="subpage.html">Search</a> | <a href="subpage.html">Books</a> | <a href="#">New Releases</a> | <a href="#">FAQs</a> | <a href="#">Contact Us</a><br>
            Copyright © 2048 <a href="#"><strong>Your Company Name</strong></a> | <a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent" title="free css templates">Free CSS Templates</a>
        </div>
        <!-- end of footer -->
        <!--  Free CSS Template www.templatemo.com -->
    </div> <!-- end of container -->
    <div align="center">This template  downloaded form <a href="http://all-free-download.com/free-website-templates/">free website templates</a></div>
</body>
</html>